# Inference
#    plot_rgb: false
#    damping: high damping
#    max_spring_force_magnitude: 50
# Data collection:
#    plot_rgb: true
#    damping: low damping
#    max_spring_force_magnitude: 15
# always check the first few parameters:
data_folder: "/home/robotlab/data/real/test_3"  # folder to save data
mock_hardware: false
bimanual: false

run_robot_thread: true
run_wrench_thread: true
run_rgb_thread: true
run_eoat_thread: false
teleop: true 
plot_rgb: false

rgb_buffer_size: 11
robot_buffer_size: 1200 #duplicado ya que los datos se leen el doble de rapido.
wrench_buffer_size: 1200 # reducido porquu la velocidad es de 1Khz 
eoat_buffer_size: 600
robot_selection: "FRANKA"  # "UR_RTDE" or "FRANKA"
camera_selection: "REALSENSE"
force_sensing_mode: "JOINT_SENSORS"
controller_selection: "IMPEDANCE_CONTROLLER"
teleop_device: "GAMEPAD"  # "GAMEPAD" or "none"
low_damping: [2.0, 2.0, 2.0, 0.1, 0.1, 0.1]
output_rgb_hw: [224, 224]

# inner joint sensor frequency (cant be changed for now because buffer synchronization)
joint_sensor_frequency: 1000


franka0:
  robot_ip: "172.17.6.164"
  log_size: 50
  tcp_mass: 0.4
  fx_c_load: [0.0, 0.0, 0.03]
  tcp_inertia: [0.1, 0.0, 0.0,
                0.0, 0.1, 0.0,
                0.0, 0.0, 0.1]
  deviation: [10.0, 3.12, 6.283185307179586]
  kDeltaT: 1e-3
  CutoffFrequency: 100
  realtime_config: "enforce" # ignore or enforce
  controller_mode: "external_controller" # "joint_impedance" or "cartesian_impedance" or "external_controller"
  motion_generator_mode: "joint_velocity" # "joint_position" or "joint_velocity" or "cartesian_position" or "cartesian_velocity"
  setJointImpedance: [3000, 3000, 3000, 2500, 2500, 2000, 2000]
  setCartesianImpedance: [1000, 1000, 1000, 200, 200, 200]
  kMaxTranslationalVelocity: 0.25
  kMaxTranslationalAcceleration: 1.0
  kMaxTranslationalJerk: 500
  kMaxRotationalVelocity: 0.25
  kMaxRotationalAcceleration: 1.0
  kMaxRotationalJerk: 500
  robot_interface_config:
    zone_safety_mode: "SAFETY_MODE_TRUNCATE"
    incre_safety_mode: "SAFETY_MODE_STOP"
    operation_mode: "OPERATION_MODE_CARTESIAN"
    max_incre_m: 0.03
    max_incre_rad: 0.2
    max_incre_joint_rad: 0.0628
    safe_zone: [-0.5, 0.7, -0.9, -0.2, 0.2, 0.8]

realsense0:
  width: 1280
  height: 720
  framerate: 30
  enable_color: true
  enable_depth: false
  align_depth_to_color: false

impedance_controller0:
  dt: 0.001
  log_to_file: false
  log_file_path: "/home/data/controller_log/impedance_controller.log"
  alert_overrun: false
  compliance6d:
    stiffness: [20, 20, 20, 20, 20, 20]
    damping: [2, 2, 2, 2, 2 ,2] # applying critical damping: D = 2*sqrt(K*m)
    nullspace_stiffness: [0, 0, 0, 0, 0, 0, 0]
    nullspace_damping: [0, 0, 0, 0, 0, 0, 0]
    stiction: [0, 0, 0, 0, 0, 0] #stationary friction model

spacemouse0:
  vendor_id: 0x256f
  product_id: 0xc635
  device_index: 0
  translation_scale: 0.8
  rotation_scale: 0.1
  dead_zone: 0.05
  enable_filtering: true
  filter_alpha: 0.3
  update_rate_hz: 1000

gamepad0:
  device_path: "/dev/input/js0"
  deadzone_stick: 0.2
  deadzone_trigger: 0.2
  update_rate_hz: 100
  translation_scale: 0.2
  rotation_scale: 0.1
